# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Import dataset

In [2]:
df = pd.read_csv('Loksabha_1962-2019 .csv')

In [3]:
df.head()

,Pc_name,no,type,state,candidate_name,party,electors,votes,Turnout,margin,margin%,year
0,Adilabad,36,GEN,Andhra Pradesh,G. Narayan Reddy,Indian National Congress,"4,04,283","2,20,383",54.5 %,"89,085",40.40%,1962.0
1,Adoni,27,GEN,Andhra Pradesh,Pendekanti Venkatasubbaiah,Indian National Congress,"4,19,077","2,52,379",60.2 %,"33,022",13.10%,1962.0
2,Agra,433,GEN,Uttar Pradesh [1947 - 1999],Seth Achal Singh,Indian National Congress,"4,33,164","2,75,663",63.6 %,"54,351",19.70%,1962.0
3,Ahmedabad,120,GEN,Gujarat,Indulal Kanaiyalal Yagnik,Nutan Maha Gujarat Janta Parisha,"4,33,392","2,70,346",62.4 %,"21,592",8.00%,1962.0
4,Ahmednagar,245,GEN,Maharashtra,Motilal Kundanmal Firodya,Indian National Congress,"4,03,913","2,22,091",55.0 %,"14,038",6.30%,1962.0

# Reviewing Dataset

In [4]:
df.shape

(8047, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8047 entries, 0 to 8046
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Pc_name         8047 non-null   object
 1   no              8047 non-null   object
 2   type            8015 non-null   object
 3   state           8047 non-null   object
 4   candidate_name  8047 non-null   object
 5   party           8047 non-null   object
 6   electors        8047 non-null   object
 7   votes           8047 non-null   object
 8   Turnout         8033 non-null   object
 9   margin          8047 non-null   object
 10  margin%         8032 non-null   object
 11  year            8046 non-null   float64
dtypes: float64(1), object(11)
memory usage: 754.5+ KB

In [6]:
df['year'].unique()

array([1962., 1967., 1971., 1977., 1980., 1984.,   nan, 1989., 1991.,
       1996., 1998., 1999., 2004., 2009., 2014., 2019.])

# Analyzing Null values

In [7]:
df.isnull().sum()

Pc_name            0
no                 0
type              32
state              0
candidate_name     0
party              0
electors           0
votes              0
Turnout           14
margin             0
margin%           15
year               1
dtype: int64

In [8]:
df[df['year'].isnull()]

,Pc_name,no,type,state,candidate_name,party,electors,votes,Turnout,margin,margin%,year
3161,No,Type,State,Winning Candidate,Party,Electors,Votes,Turnout,Margin,Margin %,NaN,NaN

In [9]:
df.drop(labels=3161,inplace=True)

In [10]:
df[df['year'].isnull()]

Empty DataFrame
Columns: [Pc_name, no, type, state, candidate_name, party, electors, votes, Turnout, margin, margin%, year]
Index: []

In [11]:
df.isnull().sum()

Pc_name            0
no                 0
type              32
state              0
candidate_name     0
party              0
electors           0
votes              0
Turnout           14
margin             0
margin%           14
year               0
dtype: int64

In [12]:
df[df['type'].isnull()]

,Pc_name,no,type,state,candidate_name,party,electors,votes,Turnout,margin,margin%,year
7521,Amalapuram,7,NaN,Andhra Pradesh [2014 Onwards],Chinta Anuradha,Yuvajana Sramika Rythu Congress Party,"11,56,280","12,32,895",108.1 %,"39,795",3.20%,2019.0
7529,Anakapalli,5,NaN,Andhra Pradesh [2014 Onwards],Dr.Beesetti Venkata Satyavathi,Yuvajana Sramika Rythu Congress Party,"13,97,335","12,38,491",91.1 %,"89,192",7.20%,2019.0
7532,Anantapur,19,NaN,Andhra Pradesh [2014 Onwards],Talari Rangaiah,Yuvajana Sramika Rythu Congress Party,"14,89,758","13,42,306",91.2 %,"1,41,428",10.50%,2019.0
7533,Anantnag,3,NaN,Jammu & Kashmir,Hasnain Masoodi,Jammu & Kashmir National Conference,"13,01,023","1,24,896",9.7 %,"6,676",5.30%,2019.0
7541,Aruku,1,NaN,Andhra Pradesh [2014 Onwards],Goddeti. Madhavi,Yuvajana Sramika Rythu Congress Party,"13,58,657","10,74,538",82.6 %,"2,24,089",20.90%,2019.0
7571,Bapatla,15,NaN,Andhra Pradesh [2014 Onwards],Nandigam Suresh,Yuvajana Sramika Rythu Congress Party,"13,61,646","12,66,492",94.0 %,"16,065",1.30%,2019.0
7574,Baramulla,1,NaN,Jammu & Kashmir,Mohammad Akbar Lone,Jammu & Kashmir National Conference,"11,90,745","4,55,550",38.9 %,"30,233",6.60%,2019.0
7637,Chittoor,25,NaN,Andhra Pradesh [2014 Onwards],N. Reddeppa,Yuvajana Sramika Rythu Congress Party,"14,30,405","13,19,472",93.7 %,"1,37,271",10.40%,2019.0
7672,Eluru,10,NaN,Andhra Pradesh [2014 Onwards],Kotagiri Sridhar,Yuvajana Sramika Rythu Congress Party,"14,18,277","13,27,923",95.3 %,"1,65,925",12.50%,2019.0
7704,Guntur,13,NaN,Andhra Pradesh [2014 Onwards],Jayadev Galla,Telugu Desam,"14,86,993","13,51,474",91.3 %,"4,205",0.30%,2019.0
7718,Hindupur,20,NaN,Andhra Pradesh [2014 Onwards],Kuruva Gorantla Madhav,Yuvajana Sramika Rythu Congress Party,"14,34,282","13,38,514",94.5 %,"1,40,748",10.50%,2019.0
7742,Jammu,6,NaN,Jammu & Kashmir,Jugal Kishore,Bharatiya Janta Party,"18,48,155","14,78,795",80.2 %,"3,02,875",20.50%,2019.0
7759,Kadapa,21,NaN,Andhra Pradesh [2014 Onwards],Y.S.Avinash Reddy,Yuvajana Sramika Rythu Congress Party,"13,25,963","12,28,242",93.7 %,"3,80,726",31.00%,2019.0
7762,Kakinada,6,NaN,Andhra Pradesh [2014 Onwards],Vanga Geethaviswanath,Yuvajana Sramika Rythu Congress Party,"14,12,538","12,34,655",88.6 %,"25,738",2.10%,2019.0
7811,Kurnool,18,NaN,Andhra Pradesh [2014 Onwards],Ayushman Doctor Sanjeev Kumar,Yuvajana Sramika Rythu Congress Party,"13,54,509","11,83,035",87.9 %,"1,48,903",12.60%,2019.0
7814,Ladakh,4,NaN,Jammu & Kashmir,Jamyang Tsering Namgyal,Bharatiya Janta Party,"1,66,763","1,26,426",76.4 %,"10,930",8.60%,2019.0
7816,Lakshadweep,1,NaN,Lakshadweep,Mohammed Faizal Pp,Nationalist Congress Party,"49,922","47,009",94.4 %,823,1.80%,2019.0
7823,Machilipatnam,11,NaN,Andhra Pradesh [2014 Onwards],Balashowry Vallabhaneni,Yuvajana Sramika Rythu Congress Party,"12,96,361","12,44,570",97.1 %,"60,238",4.80%,2019.0
7883,Nandyal,17,NaN,Andhra Pradesh [2014 Onwards],Pocha . Brahmananda Reddy,Yuvajana Sramika Rythu Congress Party,"14,02,585","12,99,093",93.3 %,"2,50,119",19.30%,2019.0
7884,Narasaraopet,14,NaN,Andhra Pradesh [2014 Onwards],Lavu Sri Krishna Devarayalu,Yuvajana Sramika Rythu Congress Party,"15,45,916","14,37,420",93.8 %,"1,54,002",10.70%,2019.0
7885,Narsapuram,9,NaN,Andhra Pradesh [2014 Onwards],Kanumuru Raghu Rama Krishna Raju,Yuvajana Sramika Rythu Congress Party,"12,94,966","11,77,738",91.9 %,"32,676",2.80%,2019.0
7889,Nellore,22,NaN,Andhra Pradesh [2014 Onwards],Adala Prabhakara Reddy,Yuvajana Sramika Rythu Congress Party,"14,60,959","12,87,036",89.3 %,"1,48,571",11.50%,2019.0
7897,Ongole,16,NaN,Andhra Pradesh [2014 Onwards],Magunta Sreenivasulu Reddy,Yuvajana Sramika Rythu Congress Party,"14,10,224","13,42,368",96.7 %,"2,14,851",16.00%,2019.0
7932,Rajahmundry,8,NaN,Andhra Pradesh [2014 Onwards],Margani Bharat,Yuvajana Sramika Rythu Congress Party,"13,82,260","12,50,427",91.8 %,"1,21,634",9.70%,2019.0
7933,Rajampet,24,NaN,Andhra Pradesh [2014 Onwards],P.V.Midhun Reddy,Yuvajana Sramika Rythu Congress Party,"14,06,762","12,24,354",88.6 %,"2,68,284",21.90%,2019.0
7991,Srikakulam,2,NaN,Andhra Pradesh [2014 Onwards],Kinjarapu Ram Mohan Naidu,Telugu Desam,"14,10,763","11,57,329",83.9 %,"6,653",0.60%,2019.0
7992,Srinagar,2,NaN,Jammu & Kashmir,Farooq Abdullah,Jammu & Kashmir National Conference,"12,05,233","1,86,832",15.6 %,"70,050",37.50%,2019.0
8013,Tirupati,23,NaN,Andhra Pradesh [2014 Onwards],Balli Durga Prasad Rao,Yuvajana Sramika Rythu Congress Party,"15,09,361","13,13,515",88.7 %,"2,28,376",17.40%,2019.0
8022,Udhampur,5,NaN,Jammu & Kashmir,Dr. Jitendra Singh,Bharatiya Janta Party,"14,90,244","11,80,123",79.7 %,"3,57,252",30.30%,2019.0
8036,Vijayawada,12,NaN,Andhra Pradesh [2014 Onwards],Kesineni Srinivas (NANI),Telugu Desam,"13,62,762","12,77,711",94.4 %,"8,726",0.70%,2019.0
8039,Visakhapatnam,4,NaN,Andhra Pradesh [2014 Onwards],M V V Satyanarayana,Yuvajana Sramika Rythu Congress Party,"15,34,088","12,39,754",81.9 %,"4,414",0.40%,2019.0
8040,Vizianagaram,3,NaN,Andhra Pradesh [2014 Onwards],Bellana Chandra Sekhar,Yuvajana Sramika Rythu Congress Party,"13,80,455","12,17,890",90.4 %,"48,036",3.90%,2019.0

In [13]:
df['type'].value_counts()

GEN     6124
SC      1241
ST       647
GENP       2
Name: type, dtype: int64

In [14]:
df['type'].fillna('GEN',inplace=True)

In [15]:
df[df['type'].isnull()]

Empty DataFrame
Columns: [Pc_name, no, type, state, candidate_name, party, electors, votes, Turnout, margin, margin%, year]
Index: []

In [16]:
df[df['Turnout'].isnull()]

,Pc_name,no,type,state,candidate_name,party,electors,votes,Turnout,margin,margin%,year
22,Angul,307,GEN,Orissa,Harekrushna Mahtab,Indian National Congress,"4,45,165",RU,NaN,RU,NaN,1962.0
454,Tehri Garhawal,360,GEN,Uttar Pradesh [1947 - 1999],Manabendra Shah,Indian National Congress,"4,15,051",RU,NaN,RU,NaN,1962.0
464,Tiruchendur,224,GEN,Madras,T. T. Krishnamachari,Indian National Congress,"4,60,766",RU,NaN,RU,NaN,1962.0
518,Anantnag,144,GEN,Jammu & Kashmir,M.S. Qureshi,Indian National Congress,1,RU,NaN,RU,NaN,1967.0
780,Kokrajhar,46,ST,Assam,R. Brahma,Indian National Congress,"4,15,618",RU,NaN,RU,NaN,1967.0
796,Ladakh,145,GEN,Jammu & Kashmir,K. Bakula,Indian National Congress,"51,381",RU,NaN,RU,NaN,1967.0
854,Nagaland,296,GEN,Nagaland,Chubatoshi,Nagaland Nationalist Organisation,"2,14,951",RU,NaN,RU,NaN,1967.0
1007,Vijayawada,13,GEN,Andhra Pradesh,K.L. Rao,Indian National Congress,"5,22,116",RU,NaN,RU,NaN,1967.0
1314,L M And A Islands,513,GEN,"Laccadive, Minicoy And Amindivi Islands",Sadanatha Mohammed Sayeed,Indian National Congress,"14,977",RU,NaN,RU,NaN,1971.0
1564,Arunachal West,1,GEN,Arunachal Pradesh,Rinchin Khandu Khimre,Indian National Congress,"1,21,887",RU,NaN,RU,NaN,1977.0
2014,Sikkim,1,GEN,Sikkim,Chatra Bahadur Chhetri,Indian National Congress,"1,24,023",RU,NaN,RU,NaN,1977.0
2571,Srinagar,2,GEN,Jammu & Kashmir,Farooq Abdullah,Jammu & Kashmir National Conference,"5,19,706",RU,NaN,RU,NaN,1980.0
2974,Mizoram,1,ST,Mizoram,Lal Dohama,Indian National Congress,"2,55,676",RU,NaN,RU,NaN,1984.0
3658,Srinagar,2,GEN,Jammu & Kashmir,Mohammad Shafi Bhat,Jammu & Kashmir National Conference,"7,82,715",RU,NaN,RU,NaN,1989.0

In [17]:
df.dropna(inplace=True)

In [18]:
df.isnull().sum()

Pc_name           0
no                0
type              0
state             0
candidate_name    0
party             0
electors          0
votes             0
Turnout           0
margin            0
margin%           0
year              0
dtype: int64

In [19]:
df.shape

(8032, 12)

# Changing dtypes

In [20]:
df.dtypes

Pc_name            object
no                 object
type               object
state              object
candidate_name     object
party              object
electors           object
votes              object
Turnout            object
margin             object
margin%            object
year              float64
dtype: object

In [21]:
df.head()

,Pc_name,no,type,state,candidate_name,party,electors,votes,Turnout,margin,margin%,year
0,Adilabad,36,GEN,Andhra Pradesh,G. Narayan Reddy,Indian National Congress,"4,04,283","2,20,383",54.5 %,"89,085",40.40%,1962.0
1,Adoni,27,GEN,Andhra Pradesh,Pendekanti Venkatasubbaiah,Indian National Congress,"4,19,077","2,52,379",60.2 %,"33,022",13.10%,1962.0
2,Agra,433,GEN,Uttar Pradesh [1947 - 1999],Seth Achal Singh,Indian National Congress,"4,33,164","2,75,663",63.6 %,"54,351",19.70%,1962.0
3,Ahmedabad,120,GEN,Gujarat,Indulal Kanaiyalal Yagnik,Nutan Maha Gujarat Janta Parisha,"4,33,392","2,70,346",62.4 %,"21,592",8.00%,1962.0
4,Ahmednagar,245,GEN,Maharashtra,Motilal Kundanmal Firodya,Indian National Congress,"4,03,913","2,22,091",55.0 %,"14,038",6.30%,1962.0

In [22]:
df['no']=pd.to_numeric(df['no'])

In [23]:
df['electors']=df['electors'].str.replace(',','')
df['votes']=df['votes'].str.replace(',','')
df['margin']=df['margin'].str.replace(',','')

In [24]:
df['Turnout']=df['Turnout'].str.replace('%','')
df.rename(columns={'Turnout':'Turnout%'},inplace=True)

In [25]:
df['margin%']=df['margin%'].str.replace('%','')

In [26]:
df.iloc[1674]

Pc_name                Daman And Diu
no                                 1
type                             GEN
state                    Daman & Diu
candidate_name    Data Not Available
party                              -
electors                           -
votes                              -
Turnout%                           -
margin                             -
margin%                            -
year                          1977.0
Name: 1684, dtype: object

In [27]:
df[df['electors']=='-']

,Pc_name,no,type,state,candidate_name,party,electors,votes,Turnout%,margin,margin%,year
1684,Daman And Diu,1,GEN,Daman & Diu,Data Not Available,-,-,-,-,-,-,1977.0
2112,Autonomous District,3,ST,Assam,Data Not Available,-,-,-,-,-,-,1980.0
2142,Barpeta,6,GEN,Assam,Data Not Available,-,-,-,-,-,-,1980.0
2227,Daman And Diu,1,GEN,Daman & Diu,Data Not Available,-,-,-,-,-,-,1980.0
2243,Dhubri,4,GEN,Assam,Data Not Available,-,-,-,-,-,-,1980.0
2246,Dibrugarh,13,GEN,Assam,Data Not Available,-,-,-,-,-,-,1980.0
2269,Gauhati,7,GEN,Assam,Data Not Available,-,-,-,-,-,-,1980.0
2333,Jorhat,12,GEN,Assam,Data Not Available,-,-,-,-,-,-,1980.0
2342,Kaliabor,11,GEN,Assam,Data Not Available,-,-,-,-,-,-,1980.0
2373,Kokrajhar,5,ST,Assam,Data Not Available,-,-,-,-,-,-,1980.0
2388,Lakhimpur,14,GEN,Assam,Data Not Available,-,-,-,-,-,-,1980.0
2416,Mangaldoi,8,GEN,Assam,Data Not Available,-,-,-,-,-,-,1980.0
2465,Nowgong,10,GEN,Assam,Data Not Available,-,-,-,-,-,-,1980.0
2552,Shillong,1,ST,Meghalaya,Data Not Available,-,-,-,-,-,-,1980.0
2583,Tezpur,9,GEN,Assam,Data Not Available,-,-,-,-,-,-,1980.0
2770,Daman And Diu,1,GEN,Daman & Diu,Data Not Available,-,-,-,-,-,-,1984.0
3199,Autonomous District,3,ST,Assam,Data Not Available,-,-,-,-,-,-,1989.0
3229,Barpeta,6,GEN,Assam,Data Not Available,-,-,-,-,-,-,1989.0
3330,Dhubri,4,GEN,Assam,Data Not Available,-,-,-,-,-,-,1989.0
3333,Dibrugarh,13,GEN,Assam,Data Not Available,-,-,-,-,-,-,1989.0
3356,Gauhati,7,GEN,Assam,Data Not Available,-,-,-,-,-,-,1989.0
3420,Jorhat,12,GEN,Assam,Data Not Available,-,-,-,-,-,-,1989.0
3429,Kaliabor,11,GEN,Assam,Data Not Available,-,-,-,-,-,-,1989.0
3438,Karimganj,1,SC,Assam,Data Not Available,-,-,-,-,-,-,1989.0
3460,Kokrajhar,5,ST,Assam,Data Not Available,-,-,-,-,-,-,1989.0
3475,Lakhimpur,14,GEN,Assam,Data Not Available,-,-,-,-,-,-,1989.0
3503,Mangaldoi,8,GEN,Assam,Data Not Available,-,-,-,-,-,-,1989.0
3552,Nowgong,10,GEN,Assam,Data Not Available,-,-,-,-,-,-,1989.0
3646,Silchar,2,GEN,Assam,Data Not Available,-,-,-,-,-,-,1989.0
3670,Tezpur,9,GEN,Assam,Data Not Available,-,-,-,-,-,-,1989.0
3729,Anantnag,3,GEN,Jammu & Kashmir,Data Not Available,-,-,-,-,-,-,1991.0
3766,Baramulla,1,GEN,Jammu & Kashmir,Data Not Available,-,-,-,-,-,-,1991.0
3950,Jammu,6,GEN,Jammu & Kashmir,Data Not Available,-,-,-,-,-,-,1991.0
4017,Ladakh,4,GEN,Jammu & Kashmir,Data Not Available,-,-,-,-,-,-,1991.0
4055,Meerut,80,GEN,Uttar Pradesh [1947 - 1999],Data Not Available,-,-,-,-,-,-,1991.0
4114,Patna,35,GEN,Bihar [1947 - 1999],Data Not Available,-,-,-,-,-,-,1991.0
4130,Purnea,24,GEN,Bihar [1947 - 1999],Data Not Available,-,-,-,-,-,-,1991.0
4201,Srinagar,2,GEN,Jammu & Kashmir,Data Not Available,-,-,-,-,-,-,1991.0
4231,Udhampur,5,GEN,Jammu & Kashmir,Data Not Available,-,-,-,-,-,-,1991.0

In [28]:
df=df[df['electors']!='-']

In [29]:
df['electors']=pd.to_numeric(df['electors'])
df['votes']=pd.to_numeric(df['votes'])
df['Turnout%']=pd.to_numeric(df['Turnout%'])
df['margin%']=pd.to_numeric(df['margin%'])

In [32]:
df.dtypes

Pc_name            object
no                  int64
type               object
state              object
candidate_name     object
party              object
electors            int64
votes               int64
Turnout%          float64
margin             object
margin%           float64
year              float64
dtype: object

In [38]:
df['year']=(df['year']).astype(int)

In [39]:
df.dtypes

Pc_name            object
no                  int64
type               object
state              object
candidate_name     object
party              object
electors            int64
votes               int64
Turnout%          float64
margin             object
margin%           float64
year                int32
dtype: object

In [40]:
df.head()

,Pc_name,no,type,state,candidate_name,party,electors,votes,Turnout%,margin,margin%,year
0,Adilabad,36,GEN,Andhra Pradesh,G. Narayan Reddy,Indian National Congress,404283,220383,54.5,89085,40.4,1962
1,Adoni,27,GEN,Andhra Pradesh,Pendekanti Venkatasubbaiah,Indian National Congress,419077,252379,60.2,33022,13.1,1962
2,Agra,433,GEN,Uttar Pradesh [1947 - 1999],Seth Achal Singh,Indian National Congress,433164,275663,63.6,54351,19.7,1962
3,Ahmedabad,120,GEN,Gujarat,Indulal Kanaiyalal Yagnik,Nutan Maha Gujarat Janta Parisha,433392,270346,62.4,21592,8.0,1962
4,Ahmednagar,245,GEN,Maharashtra,Motilal Kundanmal Firodya,Indian National Congress,403913,222091,55.0,14038,6.3,1962

In [41]:
df.to_csv('election.csv')